fragment StepTypesParts on StepTypes {
  __typename
  slug
  displayName
  description
  icon
  requiresUserInput
  hasAvatarResponse
}

fragment InputTypesParts on InputTypes {
  __typename
  slug
  displayName
  description
  allowsMultiple
  hasOptions
  validationPattern
}

fragment FlowsParts on Flows {
  __typename
  flowId
  displayName
  description
  isActive
  introVideo
  avatarIntroScript
  globalVariables {
    __typename
    brandName
  }
  steps {
    __typename
    stepId
    internalName
    order
    stepType
    introContent {
      __typename
      headline
      subheadline
      secondarySubheadline
      audioNotice
      primaryButtonText
    }
    questionContent {
      __typename
      questionText
      inputType
      helperText
      isRequired
      answerOptions {
        __typename
        optionId
        label
        value
        order
        avatarResponse
        avatarEmotion
        nextStepOverride
        terminateFlow
        terminationMessage
        tags
      }
    }
    avatarContent {
      __typename
      scriptText
      secondaryScriptText
      tertiaryScriptText
      emotion
      gestureHint
      pauseAfterMs
      autoAdvance
      autoAdvanceDelayMs
    }
    emailCaptureContent {
      __typename
      promptText
      placeholderText
      submitButtonText
      avatarResponseOnSubmit
    }
    ctaContent {
      __typename
      headline
      bodyText
      primaryButtonText
      primaryButtonUrl
      secondaryButtonText
      secondaryButtonUrl
    }
    videoContent {
      __typename
      video
      script
    }
    styling {
      __typename
      backgroundColor
      customCssClass
    }
    analytics {
      __typename
      trackingEventName
      customProperties
    }
  }
  metadata {
    __typename
    createdAt
    updatedAt
    author
    version
  }
}
