fragment StepTypesParts on StepTypes {
  __typename
  slug
  displayName
  description
  icon
  requiresUserInput
  hasAvatarResponse
}

fragment InputTypesParts on InputTypes {
  __typename
  slug
  displayName
  description
  allowsMultiple
  hasOptions
  validationPattern
}

fragment FlowsParts on Flows {
  __typename
  flowId
  displayName
  description
  isActive
  introScreen {
    __typename
    avatarImage
    backgroundVideo
    headline
    subheadline
    secondarySubheadline
    audioNotice
    primaryButtonText
  }
  globalVariables {
    __typename
    brandName
  }
  steps {
    __typename
    ... on FlowsStepsVideoStep {
      stepId
      internalName
      video
      script
    }
    ... on FlowsStepsQuestionStep {
      stepId
      internalName
      questionText
      inputType
      helperText
      isRequired
      answerOptions {
        __typename
        optionId
        label
        value
        order
        avatarResponse
        avatarEmotion
        nextStepOverride
        terminateFlow
        terminationMessage
        tags
      }
    }
    ... on FlowsStepsEmailCaptureStep {
      stepId
      internalName
      promptText
      placeholderText
      submitButtonText
      avatarResponseOnSubmit
    }
    ... on FlowsStepsSeeOptionsStep {
      stepId
      internalName
      promptText
      buttonText
      avatarMessage
      avatarEmotion
    }
    ... on FlowsStepsProductRecommendationsStep {
      stepId
      internalName
      headline
      avatarResponse
      avatarEmotion
    }
    ... on FlowsStepsZipcodeCaptureStep {
      stepId
      internalName
      headline
      placeholderText
      buttonText
    }
    ... on FlowsStepsStoreLocationsStep {
      stepId
      internalName
      headerText
      defaultPostalCode
      ctaBookTitle
      ctaBookDescription
      ctaBookButtonText
      ctaContactTitle
      ctaContactDescription
      ctaContactButtonText
    }
    ... on FlowsStepsCtaStep {
      stepId
      internalName
      headline
      bodyText
      primaryButtonText
      primaryButtonUrl
      secondaryButtonText
      secondaryButtonUrl
    }
    ... on FlowsStepsResultsStep {
      stepId
      internalName
      headline
      bodyText
    }
  }
  metadata {
    __typename
    createdAt
    updatedAt
    author
    version
  }
}
